services:
  ovgs:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_APP_NAME: OVGS
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
